#!/bin/bash

#USAGE: ***************************************
#./run-cubic-SW.sh H_diff H_n H_x H_y H_z results_directory results_prefix
#See below for descriptions of input parameters
#*********************************************

#Setting up input parameters

#Set results directory & file prefix
results_dir=$1; pref=$2

#Set field increment
H_diff=$3
#Set no. of field values from H=0 to H=max (5*H_n field values in total)
H_n=$4

#Set field direction (cartesian)
#H_x=$5; H_y=$6; H_z=$7

#Set field direction (polar)
H_theta=$5; H_phi=$6
deg2rad=$(bc -l <<< "3.14159265359/180")
echo $deg2rad
H_x=$(bc -l <<< "s($H_theta*$deg2rad)*c($H_phi*$deg2rad)"); H_y=$(bc -l <<< "s($H_theta*$deg2rad)*s($H_phi*$deg2rad)"); H_z=$(bc -l <<< "c($H_theta*$deg2rad)")

#Set temperature sweet parameters (unfinished, keep T_i=0 and T_n=1 to perform T=0 calculation)
#initial temp
T_i=0.0
#final temp
T_f=20.0
#no. of increments
T_n=1

#Declare template file
temp_file="cubic_SW.template"
temp_pref=$(echo $temp_file | sed 's/.template//g')

echo "***************************"
echo "Cubic_SW RUNNING, writing files to directory: $results_dir" 

#Create results directory if it doesn't already exist.
if [ -d "$results_dir" ] 
then
    #echo "Directory $results_dir already exists."
    :
else
    mkdir $results_dir
    #echo "Directory $results_dir created."
fi

#Setting up data files for finite temperature calculations (unfinished)
T_data=$results_dir/$pref.XvT.dat
echo "#T H mz Em" > $T_data

for (( i=0; i<($T_n); i++ ))
do
  #Calculate desired temperature and substitute into input files
  temp="$(echo "$T_i+$i*($T_f-$T_i)/$T_n" | bc -l)"
  
  #Declare full file prefix using input values & current temperature
  #file_pref=$results_dir/$pref.H-$H_x-$H_y-$H_z.T-$temp
  file_pref=$results_dir/$pref.H-$H_theta-$H_phi.T-$temp
  #Sustitute current temperature into template file and create new input file
  sed "s/temperature/$temp/g" $temp_file > $file_pref.in
  
  #Subsitute values for field sweep
  sed -i "s/H_difference/$H_diff/g" $file_pref.in
  sed -i "s/N_quad_steps/$H_n/g" $file_pref.in

  sed -i "s/HFIELDX/$H_x/g" $file_pref.in
  sed -i "s/HFIELDY/$H_y/g" $file_pref.in
  sed -i "s/HFIELDZ/$H_z/g" $file_pref.in

  # Run Lammps using input file and print output to file (MUST EDIT path to lmp_serial appropriately)
  ~/Programs/lammps/build/lmp_serial -in $file_pref.in > $file_pref.out
  
  #Extract finite temperature data from lammps averages output
  Hz="$(tail -n 1 average_spin | awk -F " " '{print $3}')"
  sz="$(tail -n 1 average_spin | awk -F " " '{print $5}')"
  en="$(tail -n 1 average_spin | awk -F " " '{print $6}')"

  #Add finite temperature data to file
  echo $temp $Hz $sz $en >> $T_data

  #Extract values relevant for field sweep
  #Write data file header
  echo "#step time v_H v_Hx v_Hy v_Hz v_magnorm v_magx v_magy v_magz v_emag etotal" > $file_pref.dat
  #Extract zero temperature data from lammps output by searching for and printing specific phrases
  grep "Minimisation" -B 50 $file_pref.out | grep Loop -B 1 | grep "^ " >> $file_pref.dat
  
  #Rename/remove output files generated by lammps 
  #log and dump files can be large, uncomment following lines if they are not needed
  #rm log.lammps
  #rm traj.$temp.dump 
  
  mv log.lammps $file_pref.log.lammps
  mv traj.$temp.dump $file_pref.traj.$temp.dump
  rm average_spin

done

echo "Cubic_SW COMPLETE, files written to $results_dir with prefix $(echo $file_pref | sed "s|.*/||g")."
echo "***************************"

